CREATE TABLE escolas (
	id integer CONSTRAINT pk_id PRIMARY KEY,
	nome_rede_ensino varchar(20),
	diretoria_ensino varchar(30),
	municipio varchar(30),
	distrito varchar(35),
	cod_escola varchar(10),
	nome_escola	varchar(100),
	situacao_escola varchar(10),
	tipo_escola varchar(40),
	endereco_escola varchar(60),
	numero_endereco	integer,
	complemento integer,
	cep integer,
	bairro varchar(57),
	zona_urbana varchar(6),
	longitude integer,
	latitude integer,
	cod_vinculadora	integer
);